### ISSUE TITLE
[FEAT] 유저 관련 API 마이그레이션

### ISSUE THREAD

**Issue by sgh002400** [sopt-makers/sopt-crew-backend#224]
## 🚀 About Issue 🚀
- 유저 상세 조회
- 유저 본인 프로필 조회
- 내가 만든 모임 조회
- 내가 신청한 모임 조회

## ✅ Todo 

- [ ] 유저 상세 조회
- [ ] 유저 본인 프로필 조회
- [ ] 내가 만든 모임 조회
- [ ] 내가 신청한 모임 조회
