### ISSUE TITLE
refactor: 시큐리티 config 개선 및 커스텀 헬스 체크 API 삭제

### ISSUE THREAD

**Issue by mikekks** [sopt-makers/sopt-crew-backend#362]
## 🚀 About Issue 🚀

- 시큐리티 config 개선 및 커스텀 헬스 체크 API 삭제

## ✅ Todo 

- [ ] 시큐리티 config 중복 코드 줄이기
- [ ] 커스텀 헬스 체크 API 삭제
- [ ] deploy 스크립트 헬스체크 엔드포인트 변경
