### ISSUE TITLE
chore: [중요] prod AWS 스크립트 수정

### ISSUE THREAD

**Issue by mikekks** [sopt-makers/sopt-crew-backend#366]
## 🚀 About Issue 🚀

- prod AWS deploy.sh 스크립트 수정
- docker-compose.yml 파일 수정
- pinpoint-agent 사용했을 때, dev-prod 충돌 없는지 확인 필요

<img width="834" alt="스크린샷 2024-09-18 오전 12 22 15" src="https://github.com/user-attachments/assets/89e17d66-c6e0-4a85-bcba-bd64537561f1">

## ✅ Todo 

- [x] prod AWS deploy.sh 스크립트 수정
- [x] docker-compose.yml 파일 수정
- [x] pinpoint-agent 사용했을 때, dev-prod 충돌 없는지 확인 필요
