### ISSUE TITLE
feat: 공동 모임장 구현

### ISSUE THREAD

**Issue by mikekks** [sopt-makers/sopt-crew-backend#447]
## 🚀 About Issue 🚀

공동 모임장 구현합니다.

## ✅ Todo 

- [x] 전체 사용자 조회 API 새로 구현
- [x] 멘션 사용자 조회 API deprecated 처리
- [x] 모임 생성 API request body 추가
- [x] 모임 수정 API request body 추가
- [x] 모임 상세 조회 API 필드 추가
- [x] 모임 상세 조회 API 공동모임장 여부 추가
- [ ] 내 모임 조회 API 로직에 공동모임장인 경우의 모임 불러오는 쿼리
- [ ] 모임 신청 시 공동모임장 여부 확인
- [x] 내 모임 조회 API 공동모임장 여부 추가
