### ISSUE TITLE
infra: NestJS 서버 내리기 작업

### ISSUE THREAD

**Issue by mikekks** [sopt-makers/sopt-crew-backend#471]
## 🚀 About Issue 🚀

- [ ] 플그 [마이페이지 내 모임 정보 조회](https://crew.api.develop.sopt.org/docs/#/%EB%AA%A8%EC%9E%84/getAllMeetingByOrgUser) 제대로 동작하는지 확인
- [ ] docker compose 확인
- [ ] deploy.sh 확인

## ✅ Todo 

- [ ] todo !
