### ISSUE TITLE
Sprint 3 기능 개발

### ISSUE THREAD

**Issue by mikekks** [sopt-makers/sopt-crew-backend#506]
## 🚀 About Issue 🚀

- SP3 기능에 맞춰 개발을 진행한다.

## ✅ Todo 

- [x] #507 
- [x] 번쩍 관련 CRUD API (cc. https://www.notion.so/sopt-makers/11de266d58294416a221d38b5a614310?pvs=4)
    - [x] 번쩍 개설 #530 
    - [x] 번쩍 상세 조회 #539 
    - [x] 번쩍 수정 #553 
    - [x] 번쩍 삭제 (기존 모임 삭제 API 로직 추가 (카테고리가 번쩍이면 flash, tag 테이블 정보 함께 삭제하도록)) #550 
- [x] #521
